[package]
name = "tanimate-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.126"
curses-sys = "6.0.0-2"
crossbeam = "0.8.1"
rand = "0.8.5"
